apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermicro-vod1
  labels:
    app: supermicro-vod1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermicro-vod1
  template:
    metadata:
      labels:
        app: supermicro-vod1
    spec:
      containers:
      - name: supermicro-video-on-demand1
        image: quay.io/emiliog1/openshift-nginx-hello@sha256:fb4d589d2a442445d84d5cf76aeea9a06f82096aebcd1a44c56b4e471f9750b5
        ports:
        - containerPort: 8080
